apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name : chatapp_deployment
spec :
    replicas: 2
    template :
        metadata:
            labels:
                app: my_chatapp
        spec:
            containers:
                name: my_chatapp_container1
                image : chatapp
                ports:
                    containerPort: 80